import os
import sys
import torch
import numpy as np
import scipy.io.wavfile as wavfile
from pathlib import Path

# Add project root to python path
project_root = Path(__file__).resolve().parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from vanitas.model.vanitas import VanitasModel
from vanitas.audio.features import MelExtractor

def run_test_inference():
    checkpoint_path = "checkpoints/best_model.pt"
    output_dir = Path("/Users/dhanyamd/.gemini/antigravity/brain/12256c2f-6c4c-441f-8642-afb5c6287392/scratch")
    output_dir.mkdir(parents=True, exist_ok=True)
    output_wav_path = output_dir / "agent_response.wav"
    
    print(f"🤖 Loading checkpoint from {checkpoint_path}...")
    if not os.path.exists(checkpoint_path):
        print(f"❌ Checkpoint not found at {checkpoint_path}!")
        return

    # Load model
    device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
    print(f"Using device: {device}")
    
    checkpoint = torch.load(checkpoint_path, map_location=device, weights_only=False)
    config = checkpoint["config"]
    print("Model configuration:")
    print(f"  Perception dim/layers: {config.perception_dim} / {config.perception_layers}")
    print(f"  Cognition dim/layers: {config.cognition_dim} / {config.cognition_layers}")
    print(f"  Production dim/layers: {config.production_dim} / {config.production_layers}")
    
    model = VanitasModel(config)
    model.load_state_dict(checkpoint["model_state_dict"], strict=False)
    model.to(device)
    model.eval()
    print("✅ Model loaded successfully!")

    # Patch generate method to start integration from zeros instead of randn
    # This prevents uncancelled Gaussian noise from corrupting the vocoder output
    def patched_generate(self, x, steps=10):
        B, L, D = x.shape
        device = x.device
        # Use zeros instead of randn
        y = torch.zeros(B, L, self.mel_dim, device=device)
        dt = 1.0 / steps
        for i in range(steps):
            t = torch.ones(B, 1, device=device) * (i * dt)
            v_pred = self(x, t)
            y = y + v_pred * dt
        return y

    import types
    model.flow_head.generate = types.MethodType(patched_generate, model.flow_head)
    print("🩹 Patched FlowMatchingHead.generate to eliminate residual noise.")

    # 1. Generate synthetic user input (vowel sound 'ah' at 220Hz + 440Hz harmonic)
    sample_rate = 16000
    duration = 3.0  # 3 seconds of user speech
    t = np.linspace(0, duration, int(sample_rate * duration), endpoint=False)
    user_audio = 0.5 * np.sin(2 * np.pi * 220 * t) + 0.25 * np.sin(2 * np.pi * 440 * t)
    # Add minor noise
    user_audio += np.random.normal(0, 0.01, len(user_audio))
    user_audio = user_audio.astype(np.float32)

    # 2. Extract Mel Features
    extractor = MelExtractor(
        sample_rate=sample_rate,
        n_fft=400,
        hop_length=160,
        win_length=400,
        n_mels=config.mel_bins
    )
    user_mel = extractor.feed_audio(user_audio).to(device) # (1, T, n_mels)
    print(f"User input audio length: {duration}s -> Mel shape: {user_mel.shape}")

    # 3. Create dummy agent mel history (silence / pad)
    agent_mel = torch.full_like(user_mel, -5.0) # -5.0 is silence in log-mel space

    # 4. Create RAG memory query embeddings
    memory_embeddings = torch.zeros(1, 0, config.memory_dim, device=device)

    # 5. Run forward pass
    print("🧠 Running model forward pass (inference mode)...")
    with torch.no_grad():
        outputs = model(user_mel, agent_mel_frames=agent_mel, memory_embeddings=memory_embeddings)
        
        audio = outputs["audio"]
        think_gate = outputs["think_gate"]
        speak_gate = outputs["speak_gate"]
        
    print("📊 Inference Gates results:")
    print(f"  Think Gate (average/max): {think_gate.mean().item():.4f} / {think_gate.max().item():.4f}")
    print(f"  Speak Gate (average/max): {speak_gate.mean().item():.4f} / {speak_gate.max().item():.4f}")

    if audio is not None:
        generated_audio = audio.cpu().numpy().flatten()
        print(f"🔊 Generated audio waveform: {len(generated_audio)} samples (~{len(generated_audio)/sample_rate:.2f}s)")
        
        # Save output wav
        wavfile.write(output_wav_path, sample_rate, generated_audio)
        print(f"🎉 Saved agent audio response to: {output_wav_path}")
    else:
        print("❌ No audio generated by the model.")

if __name__ == "__main__":
    run_test_inference()
